### ISSUE TITLE
replace "canonical", "local" with clearer names

### ISSUE THREAD

**Issue by rsc** [kardianos/vendor-spec#32] opened 2015-08-28 16:16 UTC
I find these names confusing. I understand "local" but not "canonical". If one is "local" it seems like the other must be "remote". Using "canonical" implies that the entry says the canonical copy of the relevant package, but it might not be. It might be a forked copy with modifications. The example on the front page illustrates the problem:

```
    {
        "canonical": "crypto/tls",
        "local": "vendor/crypto/tls",
        "revision": "80a4e93853ca8af3e273ac9aa92b1708a0d75f3a",
        "revisionTime": "2015-04-07T09:07:15-07:00",
        "originPath": "github.com/MSOpenTech/azure-sdk-for-go/internal/crypto/tls",
        "originURL": "https://github.com/Azure/azure-sdk-for-go.git",
        "comment": "located on disk at $GOPATH/src/github.com/kardianos/mypkg/vendor/crypto/tls"
    },
```

If this is saying that ./vendor/crypto/tls is copied from the azure sdk, then I expected that path to be the "canonical". (I filed a separate issue about originPath/originURL.) So I am guessing that this should say:

```
    {
        "canonical": "github.com/MSOpenTech/azure-sdk-for-go/internal/crypto/tls",
        "local": "vendor/crypto/tls",
        "revision": "80a4e93853ca8af3e273ac9aa92b1708a0d75f3a",
        "revisionTime": "2015-04-07T09:07:15-07:00",
        "comment": "located on disk at $GOPATH/src/github.com/kardianos/mypkg/vendor/crypto/tls"
    },
```

While that may be the remote source for the code there is really very little "canonical" about it, so this name doesn't really make sense.

"local" and "remote" would be very clear: local is the local file system location, and remote is the remote source control location. However, with those names resolving #29 is awkward, because it's not obvious which one should be the required field vs the optional field.

It might make more sense to use "path" for "local" and "origin" for "remote"/"canonical". Then "origin" can be omitted when it is the same as "path".

That is, the general form would be (switching examples to something more usual):

```
{
    "origin": "rsc.io/pdf",
    "path": "rsc.io/pdf",
    "revision": "371ad118eb63f9f52971201c4e903420401ed37f",
    "revisionTime": "2015-07-23T06:11:39Z"
}
```

and this could be abbreviated by omitting origin when it matches path (and ideally revisionTime, see #30):

```
{
    "path": "rsc.io/pdf",
    "revision": "371ad118eb63f9f52971201c4e903420401ed37f"
}
```

The crypto/tls example would read (assuming #28):

```
    {
        "origin": "github.com/MSOpenTech/azure-sdk-for-go/internal/crypto/tls",
        "path": "crypto/tls",
        "revision": "80a4e93853ca8af3e273ac9aa92b1708a0d75f3a"
    }
```

**Comment by kardianos** [comment] 2015-08-28 16:51
You are the second person who was confused by those names, so I agree, lets change them.

"local" will now always be the same as "canonical" (#28), "canonical" is now "path", "origin" is a new field showing where the package came from. If "origin" is empty or not present then the value of "origin" can be treated as the same value as "path".

**Comment by rsc** [comment] 2015-08-28 18:01
Given your reply it sounds like I didn't even understand the original names. I'll watch for the update and check and see if I understand the new ones. :-)

**Comment by mattfarina** [comment] 2015-08-29 10:57
Why are there two names?

My suggestion, taken from working with numerous package managers, would be `package`. These are the package names as we used them today with tools like `go get`, right? That name could be used to set the path in the `$GOPATH`.

For the remote end of it, what about `repository` and have a `type` there to support any tooling. That could optionally specify the rep to get the package from. This would work for forks, private repos, etc.

These types of names show up in other package managers which may make it easier for people who use multiple languages or have switched to Go from one of those.

**Comment by kardianos** [comment] 2015-08-29 15:04
@mattfarina Thank you for the suggestions.

Everything in the package object is talking about a package. Thus "path" as suggested by russ reads: "package.path".

I have seen others suggest recording the remote repository type ("git", "hg", etc) but I've rejected such notions before for the same reason "go get" doesn't usually need help determining the repository type. At the end of the day it shouldn't matter if you've changed from "hg" to "git" to "perforce".  Note I'm not totally against such a suggestion, just when reading numerous vendor tools source, the go tool source, and creating my own vendor tool, this information just doesn't matter.

"package.origin" says where this package is from, which makes a difference, especially if local changes were made from that source (I've encountered this in practice).

As much as possible, I want to stay away from recording "repositories" and stick with package paths. The reason you indicate repository is what I believe Russ is proposing "package.origin" for.

**Comment by mattfarina** [comment] 2015-08-29 20:13
So, you're suggesting only using origin paths that the magic in `go get` can do?

What about the case where you want to have another repo checked out in your vendor directory and you want to push to it? Where the repo may be a repo rather than a package part (e.g., `git@github.com/foo/bar`)?

**Comment by kardianos** [comment] 2015-08-29 23:01
Specifically, what `http://godoc.org/golang.org/x/tools/go/vcs` provides.

If you have a full dvcs repository in the vendor dir, then you can push already. If you don't, then you will probably want a tool to do some type of "backport" command to a repo elsewhere on disk.

**Comment by mattfarina** [comment] 2015-08-31 13:18
@kardianos How do you get the full VCS repo in the `vendor/` directory? If you want multiple people, such as a team working on an internal project, to get it in a repeatable manner how would you do that? `golang.org/x/tools/go/vcs` doesn't provide that today.

**Comment by kardianos** [comment] 2015-08-31 15:41
@mattfarina I don't understand this question. My 8mo old is still not sleeping the whole night so I could just be sleepy. Are you wanting to copy ".git" and ".hg" folders into the "vendor" directory and check them in? Are you wanting to copy the entire repo into the "vendor" directory?

In my above comment `golang.org/x/tools/go/vcs` resolves an import path into a fetchable repository path. You are correct it doesn't currently support the "vendor" folder. For the time being I might fork it until such support is added.

**Comment by mattfarina** [comment] 2015-08-31 16:44
@kardianos I remember the days my kids kept me up at night. I understand.

Here is an example situation I've seen time and time again...

Imagine you have an application that uses an SDK. You're developing both at the same time and you have a small team. They are separate from each other. The application name is `foo/bar` and the sdk is `foo/baz` (for lack of better names).

To work on both you're not vendoring (that is storing `foo/baz` inside `foo/bar`) but instead making sure `foo/baz` is checked out properly inside the `vendor/` folder so that you can push to it when needed. How would you go about doing that?

With Glide we'd have something like:

``` yaml
package: foo/bar
imports:
- package: github.com/foo/baz
  repo: git@github.com:foo/baz.git
  vcs: git
```

This would work if you need to push to `foo/baz` and for cases you're working with private repos.

Any setup should be flexible enough to handle all those cases.

Does that help? Note, the stuff here is an example. I'm more interested in the ideas being shared that any particular format or tool.

**Comment by kardianos** [comment] 2015-08-31 17:03
@mattfarina If you are developing them in lock step, then I would just have them both in GOPATH. When you finally release "foo/bar" I would vendor a snapshot of "foo/baz" from GOPATH into the "vendor" folder.

Some people would choose to address keeping them in lock step by putting them in the same (mono?) repo. This is very popular for some companies (yes, even non-google).

If they are in different repositories, then either developers need to pull from tip from both while they are unstable. This is true whether "foo/baz" is found in GOPATH or "vendor". Today without the vendor folder running "go get -u github.com/foo/bar" will checkout the latest from tip for the "bar" as well as "baz".

Unless I'm mistaken, the desired workflow you want to support is already supported today.

**Comment by mattfarina** [comment] 2015-08-31 17:12
@kardianos how would you handle the case of developing a 2.x version (that's breaking API compatibility) while also having you're 1.x version around for use in other apps. I can think of SDK development this way and it's a real case.

Having it in your GOPATH also doesn't solve setting up the git repo in a reproducible manner across all the developers. Each one of them still needs to make the directories and `git clone` the repo.

Does that make sense?

**Comment by kardianos** [comment] 2015-08-31 17:25
I'm fairly sure that `go get -u github.com/foo/bar` willl do all the "git clone" you need, even for privte repos if you have the keys in your ssh agent or https auth stored.

I would handle developing a 2.x version the same way as any other piece of code I suppose. Work on the new branch in GOPATH. If 1.x  needs fixing then `git checkout v1.x` and do the fix. Dependent packages that rely on the released 1.x branch should already have them in the "vendor" folder (not necessarily checked in). govendor or glide will then ensure the files get checkout into "vendor".

I think it makes sense, I just don't see the problem.

**Comment by mattfarina** [comment] 2015-08-31 17:35
'go get -u github.com/foo/bar`for a private repo will try to get it from`https://github.com/foo/bar`. You'll need to use your github credentials rather than keys to handle that.

If you're regularly building packages using 2 different versions of the same project, how do you automate that? Having to use `git checkout v2.x` before and build and `git checkout v1.x` before another build is a very manual thing. Shouldn't the tooling support automating this?

**Comment by rsc** [comment] 2015-08-31 17:39
I think this discussion is diverging a little bit. Additional metadata might be recorded, but my understanding of the vendor.json file was that the basic pieces say "I copied <this> from <over there>", where "<this>" is relative to the current directory (what I suggested to be called "path") and "<over there>" is found in the main $GOPATH (outside any vendor directory; what I suggested to be called "origin"). The exact rules for resolving "origin" may not be relevant to the vendoring tool. 

Certainly there could be resolution rules for remote references in a particular vendoring tool, but it seems to me a cleaner separation of concerns to let the go command deal with that and make vendoring just record "this came from over there". And "go get" does have the ability to name arbitrary git (or other) repos, so I don't agree that the set of nameable repos is somehow restricted by delegating those semantics to the existing conventions. The general syntax is "blah.com/blah/blah.git/dir/dir/dir", which names the repo "blah.com/blah/blah.git" and the directory "dir/dir/dir" within that repo.

**Comment by mattfarina** [comment] 2015-08-31 18:11
@rsc the I copied from one path to another path (relatively speaking) feels kludgy compared to the tools and definitions the other languages have. I would suggest something more elegant gained from the lessons learned in the other tools. I'll try to put a better explanation together in the next couple days.

**Comment by rsc** [comment] 2015-08-31 19:01
It really comes down to: do you want to bake in a specific resolution
algorithm into this spec? I believe the answer is no, that that is a
separate concern. Go has in general gotten very good results from working
to separate concerns like these from each other, so that you can innovate
in the two separately rather than building "integrated" tools that do
everything and lock you into "all or nothing" scenarios.

**Comment by mattfarina** [comment] 2015-08-31 19:19
@rsc A spec, like the one here, being recommended as part of Go itself will set a direction for `vendor/` dependencies. It could quickly set a standard that doesn't handle many use cases. That's my concern. I'd rather wait, set clear separations, or not implement something in Go if it's going to create issues.

**Comment by rsc** [comment] 2015-08-31 19:31
What use case specifically does it not handle?

**Comment by mattfarina** [comment] 2015-08-31 19:47
@rsc Let's move this conversation elsewhere. I'll get you some clearer thoughts in the next couple days. I'm going to try to write something up and have a couple others, some who know the way you do things at Google, look it over to make sure I'm clearly communicating my thoughts.

**Comment by rsc** [comment] 2015-08-31 20:40
@mattfarina thanks, let's move this to the golang-dev thread you started.
I'll wait for your reply.

Russ

**Closed as completed** 2015-09-01 03:57 UTC
